version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8091:8080
      - 50003:50000
    container_name: my-jenkins-5
    volumes:
      - C:\Users\Nancy\OneDrive\Desktop\Devops_roadmap\jenkins_hello1:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
